const IMG={"4190": "assets/img/work-4190.jpg", "4184": "assets/img/work-4184.jpg", "4183": "assets/img/work-4183.jpg", "4180": "assets/img/work-4180.jpg", "4178": "assets/img/work-4178.jpg", "4175": "assets/img/work-4175.jpg", "4173": "assets/img/work-4173.jpg", "4174": "assets/img/work-4174.jpg", "4171": "assets/img/work-4171.jpg", "4165": "assets/img/work-4165.jpg", "4182": "assets/img/work-4182.jpg", "4186": "assets/img/work-4186.jpg", "4201": "assets/img/work-4201.jpg", "4200": "assets/img/work-4200.jpg", "4196": "assets/img/work-4196.jpg", "4198": "assets/img/work-4198.jpg", "4195": "assets/img/work-4195.jpg", "4185": "assets/img/work-4185.jpg"};
const ES={"What We Make":"Lo Que Hacemos","Pricing":"Precios","Our Work":"Nuestro Trabajo","About":"Nosotros","Contact":"Contacto","Call Now":"Llamar Ahora","Email Us":"Escríbenos","Email":"Correo","Call or text":"Llama o envía mensaje",
h1:"Ropa Personalizada, Calcomanías para Vehículos, <em>Gorras y Más !</em>",hp:"De ropa a letreros — lo hacemos todo. Camisas, sudaderas, termos, gorras, placas, gráficos para vehículos e impresión, hechos con cuidado.",
"View Our Work":"Ver Nuestro Trabajo","See Products & Pricing":"Productos y Precios","High Quality Products":"Productos de Alta Calidad","Great Prices":"Buenos Precios","Fast & Friendly Service":"Servicio Rápido y Amable",
"One shop. Everything custom.":"Un solo taller. Todo personalizado.","Browse by category — each piece is decorated with your logo, team name or design.":"Explora por categoría — cada pieza lleva tu logo, nombre de equipo o diseño.",
"Straightforward prices.":"Precios claros.",note:"Precios según nuestras listas actuales. Otros tamaños y trabajos personalizados disponibles — el precio varía. Llama o escríbenos para más detalles.",
"Portfolio":"Portafolio","See our work.":"Mira nuestro trabajo.","Tap any image to view it larger.":"Toca una imagen para verla más grande.","Our work in action":"Nuestro trabajo en acción","Copy Email":"Copiar Correo","Tap to copy":"Toca para copiar","Copied!":"¡Copiado!","Follow us":"Síguenos","Truck lettering":"Rotulación de camioneta","Van graphics":"Gráficos para vans","Truck graphics":"Gráficos para camioneta","Truck decals":"Calcomanías para camioneta","Installing a decal":"Instalando una calcomanía","Custom shirt print":"Estampado de camisa","Custom shirts & hats":"Camisas y gorras personalizadas","Custom decals":"Calcomanías personalizadas",
"About Us":"Sobre Nosotros","Small shop. Big attention to detail.":"Taller pequeño. Gran atención al detalle.",a1:"CNC Custom Designs LLC es un negocio familiar. Creemos que el trabajo personalizado debe verse bien, llegar rápido y costar lo justo — ya sea una docena de camisas para tu equipo o gráficos para toda la camioneta.",a2:"Cada pedido lo atienden personas a quienes les importa el resultado. Creaciones personalizadas hechas con cariño.",
"Quality you can feel":"Calidad que se siente","Fair pricing":"Precios justos","Friendly service":"Servicio amable",ord:'Para Ordenar Llámanos o Envíanos un Mensaje al <a href="#" role="button" data-copy="502-417-2912">502-417-2912</a> !',
"From apparel to signs — we make it all!":"De ropa a letreros — ¡lo hacemos todo!","See pricing →":"Ver precios →","All":"Todo","Hats":"Gorras","Vehicles":"Vehículos","Signs & Cards":"Letreros y Tarjetas",
"Apparel":"Ropa","Drinkware":"Termos y Tazas","Headwear":"Gorras","Other":"Otros","Signs & Print":"Letreros e Impresión",
"Shirts — Cotton":"Camisas — Algodón","Shirts — Polyester":"Camisas — Poliéster","Per dozen":"Por docena","Short Sleeve":"Manga Corta","Long Sleeve":"Manga Larga","Short Sleeve w/ Collar (Polo)":"Manga Corta con Cuello (Polo)","Long Sleeve w/ Hood":"Manga Larga con Capucha",
"Sweatshirts":"Sudaderas","50% cotton / 50% polyester":"50% algodón / 50% poliéster","With Hood":"Con Capucha","Without Hood (Crewneck)":"Sin Capucha (Cuello Redondo)","Mugs & tumblers":"Tazas y termos","12 oz Coffee Mug":"Taza de Café 12 oz","20 oz Tumbler, No Handle":"Termo 20 oz, Sin Asa","20 oz Tumbler, With Handle":"Termo 20 oz, Con Asa",
"Caps & visors":"Gorras y viseras","Cap":"Gorra","Sunvisor":"Visera","License Plate & Frame":"Placas y Marcos","Custom printed":"Impresión personalizada","License Plate":"Placa","License Plate Frame":"Marco de Placa",
"Vehicle Graphics":"Gráficos para Vehículos","Starting at":"Desde","2 Door Trucks":"Camionetas 2 Puertas","4 Door Trucks":"Camionetas 4 Puertas","Mini Van":"Minivan","Work Van":"Van de Trabajo","Large Trailer":"Remolque Grande","Small Trailer":"Remolque Pequeño",
"Car Magnets":"Imanes para Carro","By size":"Por tamaño","Business Cards":"Tarjetas de Presentación","Yard Signs":"Letreros de Jardín","Orders of 6+ : $18 each":"Pedidos de 6 o más: $18 c/u","Single Sided":"Una Cara","Double Sided":"Dos Caras","Door Hangers":"Colgadores de Puerta","Vinyl Stickers":"Calcomanías de Vinil",'2"–4" · other sizes, price varies':'2"–4" · otros tamaños, el precio varía',
"each":"c/u","dozen":"docena","from":"desde",
"Custom T-shirts":"Camisetas personalizadas","Hoodies":"Sudaderas con capucha","Custom caps":"Gorras personalizadas","Vehicle & trailer graphics":"Gráficos para vehículos y remolques","Car magnets":"Imanes para carro","Business cards":"Tarjetas de presentación","Yard signs":"Letreros de jardín","Tumblers":"Termos","Caps & shirts":"Gorras y camisas",
c_Apparel:"Camisetas (algodón o poliéster, manga corta o larga, polos, con capucha), sudaderas con y sin capucha.",c_Drinkware:"Tazas de café de 12 oz y termos de 20 oz, con o sin asa.",c_Headwear:"Gorras y viseras personalizadas.",c_Other:"Placas y marcos de placa personalizados.","c_Signs & Print":"Gráficos para vehículos, imanes, tarjetas, letreros de jardín, colgadores de puerta y calcomanías."};
const EN={c_Apparel:"Custom T-shirts (cotton or polyester, short or long sleeve, polos, hooded), hoodies and crewnecks.",c_Drinkware:"12 oz coffee mugs and 20 oz tumblers, with or without handle.",c_Headwear:"Custom caps and sun visors.",c_Other:"Custom license plates and license plate frames.","c_Signs & Print":"Vehicle graphics, car magnets, business cards, yard signs, door hangers and stickers."};
let L="en";try{L=localStorage.getItem("l")||((navigator.language||"").slice(0,2)=="es"?"es":"en")}catch(e){}
const tr=s=>{if(L!="es")return EN[s]||s;if(ES[s])return ES[s];return s.replace("Cards","Tarjetas").replace("Hangers","Colgadores").replace("Stickers","Calcomanías")};
const VID=["assets/video/clip-1.mp4", "assets/video/clip-2.mp4", "assets/video/clip-3.mp4", "assets/video/clip-4.mp4", "assets/video/clip-5.mp4", "assets/video/clip-6.mp4", "assets/video/clip-7.mp4", "assets/video/clip-8.mp4", "assets/video/clip-9.mp4", "assets/video/clip-10.mp4"],VP=["assets/img/poster-1.jpg", "assets/img/poster-2.jpg", "assets/img/poster-3.jpg", "assets/img/poster-4.jpg", "assets/img/poster-5.jpg", "assets/img/poster-6.jpg", "assets/img/poster-7.jpg", "assets/img/poster-8.jpg", "assets/img/poster-9.jpg", "assets/img/poster-10.jpg"];
const VC=["Truck lettering","Van graphics","Van graphics","Van graphics","Truck graphics","Truck decals","Installing a decal","Custom shirt print","Custom shirts & hats","Custom decals"];
const $=s=>document.querySelector(s);
const D={Apparel:[["Shirts — Cotton","Per dozen",[["Short Sleeve",220],["Long Sleeve",240],["Short Sleeve w/ Collar (Polo)",250],["Long Sleeve w/ Hood",260]],"d"],["Shirts — Polyester","Per dozen",[["Short Sleeve",230],["Long Sleeve",250],["Short Sleeve w/ Collar (Polo)",260],["Long Sleeve w/ Hood",270]],"d"],["Sweatshirts","50% cotton / 50% polyester",[["With Hood",35],["Without Hood (Crewneck)",22]],"e"]],
Drinkware:[["Drinkware","Mugs & tumblers",[["12 oz Coffee Mug",12],["20 oz Tumbler, No Handle",20],["20 oz Tumbler, With Handle",35]],"e"]],Headwear:[["Hats","Caps & visors",[["Cap",22],["Sunvisor",18]],"e"]],Other:[["License Plate & Frame","Custom printed",[["License Plate",20],["License Plate Frame",23]],"e"]],
"Signs & Print":[["Vehicle Graphics","Starting at",[["2 Door Trucks",250],["4 Door Trucks",350],["Mini Van",300],["Work Van",400],["Large Trailer",500],["Small Trailer",300]],"f"],["Car Magnets","By size",[["18x12",35],["24x12",45],["24x18",55]],""],["Business Cards","",[["250 Cards",75],["500 Cards",95],["1000 Cards",120]],""],["Yard Signs","Orders of 6+ : $18 each",[["Single Sided",20],["Double Sided",25]],"e"],["Door Hangers","",[["50 Hangers",100],["100 Hangers",150],["200 Hangers",225]],""],["Vinyl Stickers",'2"–4" · other sizes, price varies',[["50 Stickers",80],["100 Stickers",110],["150 Stickers",150],["200 Stickers",175],["300 Stickers",230]],""]]};
const U={d:()=>` <i>/${tr("dozen")}</i>`,e:()=>` <i>${tr("each")}</i>`,f:()=>"","":()=>""};
const card=c=>`<article class="card in"><h3>${tr(c[0])}</h3><small>${tr(c[1])||"&nbsp;"}</small><ul>${c[2].map(i=>`<li><span>${tr(i[0])}</span><b>${c[3]=="f"?tr("from")+" ":""}$${i[1]}${U[c[3]]()}</b></li>`).join("")}</ul></article>`;
const io=new IntersectionObserver(e=>e.forEach(x=>{if(x.isIntersecting){x.target.classList.add("in");io.unobserve(x.target)}}),{threshold:.1});
const obs=()=>document.querySelectorAll(".rv:not(.in)").forEach(e=>io.observe(e));
let tab="Apparel",flt="all";
const T={tee:["Custom T-shirts","apparel"],hood:["Hoodies","apparel"],cap:["Custom caps","hats"],capt:["Caps & shirts","hats"],veh:["Vehicle & trailer graphics","vehicles"],mag:["Car magnets","vehicles"],card:["Business cards","print"],sign:["Yard signs","print"],tum:["Tumblers","drinkware"]};
const G=[["4190","HCV Drywall","tee"],["4184","Jimenez Tree Removal","tee"],["4183","JV Drywall","cap"],["4180","Castillo Construction","capt"],["4178","Nunn's Drywall","tee"],["4175","D&D Diaz Home Services","veh"],["4173","Richard Remodeling","tee"],["4174","Sacor Construction","tee"],["4171","Altamirano Painting","hood"],["4165","Hidalgo","hood"],["4182","Marquez Painting","card"],["4186","Morale's Remodeling","card"],["4201","Castillo Construction","tum"],["4200","Astromotor","veh"],["4196","Altamirano Painting","mag"],["4198","Mabella Construction","mag"],["4195","Mata's Remodeling","sign"],["4185","D. Gem 4 Construction","sign"]];
const CH=[["all","All"],["apparel","Apparel"],["hats","Hats"],["drinkware","Drinkware"],["vehicles","Vehicles"],["print","Signs & Cards"]];
$("#vids").innerHTML=VC.map((c,i)=>`<figure><video controls playsinline preload="none" poster="${VP[i]}" src="${VID[i]}"></video><figcaption data-t="${c}">${c}</figcaption></figure>`).join("");
function toast(){const t=$("#toast");t.textContent=tr("Copied!");t.classList.add("on");clearTimeout(toast.h);toast.h=setTimeout(()=>t.classList.remove("on"),1800)}
document.addEventListener("click",e=>{const c=e.target.closest("[data-copy]");if(!c)return;e.preventDefault();const v=c.dataset.copy,fb=()=>{const a=document.createElement("textarea");a.value=v;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();try{document.execCommand("copy")}catch(x){}a.remove();toast()};
if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(v).then(toast,fb);else fb()});
function render(){
document.documentElement.lang=L;$("#lg").textContent=L=="es"?"EN":"ES";$("#lg").setAttribute("aria-label",L=="es"?"Switch to English":"Cambiar a español");
document.querySelectorAll("[data-t]").forEach(e=>{if(!e.dataset.en)e.dataset.en=e.innerHTML;const k=e.dataset.t;e.innerHTML=L=="es"&&ES[k]?ES[k]:e.dataset.en});
const ks=["Apparel","Drinkware","Headwear","Other","Signs & Print"];
$("#cats").innerHTML=ks.map(k=>`<article class="card in"><h3>${tr(k)}</h3><small>&nbsp;</small><p style="margin:0;color:var(--mut)">${tr("c_"+k)}</p><p style="margin:14px 0 0"><a href="#pricing" data-k="${k}" style="color:var(--red);font-weight:600;text-decoration:none">${tr("See pricing →")}</a></p></article>`).join("");
$("#tabs").innerHTML=ks.map(k=>`<button class="tab" role="tab" data-k="${k}" aria-selected="${k==tab}">${tr(k)}</button>`).join("");
$("#prices").innerHTML=D[tab].map(card).join("");
$("#chips").innerHTML=CH.map(c=>`<button class="tab" data-f="${c[0]}" aria-pressed="${c[0]==flt}" aria-selected="${c[0]==flt}">${tr(c[1])}</button>`).join("");
$("#gal").innerHTML=G.filter(g=>flt=="all"||T[g[2]][1]==flt).map(g=>`<button class="rv in" data-k="${g[0]}" aria-label="${g[1]} — ${tr(T[g[2]][0])}"><img loading="lazy" src="${IMG[g[0]]}" alt="${g[1]} — ${T[g[2]][0]}"><span>${g[1]} · ${tr(T[g[2]][0])}</span></button>`).join("")}
document.addEventListener("click",e=>{const a=e.target.closest("[data-k],[data-f]");if(!a||a.closest("#gal"))return;if(a.dataset.f)flt=a.dataset.f;else tab=a.dataset.k;render()});
const lb=$("#lb");$("#gal").onclick=e=>{const b=e.target.closest("button");if(!b)return;const g=G.find(x=>x[0]==b.dataset.k),i=lb.querySelector("img");i.src=IMG[g[0]];i.alt=g[1];lb.querySelector("p").textContent=g[1]+" · "+tr(T[g[2]][0]);lb.showModal()};
lb.onclick=e=>{if(e.target==lb||e.target.className=="x")lb.close()};
$("#lg").onclick=()=>{L=L=="es"?"en":"es";try{localStorage.setItem("l",L)}catch(e){}render()};
const hd=$("#hd"),bg=$("#bg"),lk=$("#lk");
addEventListener("scroll",()=>hd.classList.toggle("s",scrollY>40),{passive:true});
const tg=o=>{lk.classList.toggle("o",o);bg.setAttribute("aria-expanded",o)};
bg.onclick=()=>tg(!lk.classList.contains("o"));lk.onclick=e=>{if(e.target.tagName=="A")tg(false)};
addEventListener("keydown",e=>{if(e.key=="Escape")tg(false)});
$("#yr").textContent=new Date().getFullYear();render();obs();
